name: CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'admin/**'
  workflow_dispatch:

jobs:
  deploy-frontend:
    if: always()
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step : Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Step 2: Deploy to Hostinger
      - name: Deploy Frontend
        run: |
          sshpass -p "${{ secrets.HOSTINGER_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_HOST_USER }} << 'EOF'
          cd mangomart/frontend
          git pull origin main
          npm install
          npm run build
          pm2 delete frontend || true
          pm2 start "npm run dev" --name "frontend"
          pm2 save
          EOF

  deploy-admin:
    if: always()
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step : Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Step 2: Deploy to Hostinger
      - name: Deploy Admin
        run: |
          sshpass -p "${{ secrets.HOSTINGER_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_HOST_USER }} << 'EOF'
          cd mangomart/admin
          git pull origin main
          npm install
          npm run build
          pm2 delete admin || true
          pm2 start "npm run dev" --name "admin"
          pm2 save
          EOF

  deploy-backend:
    if: always()
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step : Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Step 2: Deploy to Hostinger
      - name: Deploy Backend
        run: |
          sshpass -p "${{ secrets.HOSTINGER_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_HOST_USER }} << 'EOF'
          cd mangomart/backend
          git pull origin main
          npm install
          pm2 delete backend || true
          pm2 start ./src/server.js --name "backend"
          pm2 save
          EOF
 